In [11]:
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold, KFold, StratifiedKFold

In [6]:
a = pd.read_csv('dataset/split/train_fold_0_seed_960630.csv')['0']

In [7]:
a

0         VP097/R001.png
1         VP097/R208.png
2         VP097/R041.png
3         VP097/R085.png
4         VP097/R190.png
              ...       
11041    VNS007/L182.png
11042    VNS007/L092.png
11043    VNS007/L190.png
11044    VNS007/L109.png
11045    VNS007/L097.png
Name: 0, Length: 11046, dtype: object

In [12]:
c = np.arange(10)

In [13]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
d = a.iloc[c]

In [16]:
'a'+d[0]

'aVP097/R001.png'

In [17]:
for i, j in enumerate(d):
    print(i, 'a/'+j)

0 a/VP097/R001.png
1 a/VP097/R208.png
2 a/VP097/R041.png
3 a/VP097/R085.png
4 a/VP097/R190.png
5 a/VP097/R123.png
6 a/VP097/R044.png
7 a/VP097/R007.png
8 a/VP097/R158.png
9 a/VP097/R139.png


In [43]:
df.columns.values

array([0])

In [57]:
kf = KFold(n_splits=2)

In [90]:
def get_train_val_split(data_path="../Carotid-Data/Carotid-Data/images/", 
                        save_path="dataset/",
                        n_splits=5, 
                        seed=960630):
    os.makedirs(save_path + 'split/', exist_ok=True)
    kf = KFold(n_splits=n_splits, random_state=seed, shuffle=True)
    df = pd.DataFrame(os.listdir(data_path))
    for fold, (train_idx, val_idx) in enumerate(kf.split(df)):
        train_df, val_df = [], []
        for image_dir in df.iloc[train_idx].values:
            image_ids = os.listdir(data_path+image_dir[0])
            for image_id in image_ids:
                train_df.append(image_dir[0]+'/'+image_id)

        for image_dir in df.iloc[val_idx].values:
            image_ids = os.listdir(data_path+image_dir[0])
            for i in range(len(image_ids)):
                val_df.append(image_dir[0]+'/'+image_ids[i])
        
        pd.DataFrame(train_df).to_csv(save_path + 'split/' + '/train_fold_%s_seed_%s.csv'%(fold, seed))
        pd.DataFrame(val_df).to_csv(save_path + 'split/' + '/val_fold_%s_seed_%s.csv'%(fold, seed))
      
    return
#         print(fold,image_ids[0]+'/'+image_ids)
#         print(os.listdir("../Carotid-Data/Carotid-Data/images/"+x[0]))

In [91]:
get_train_val_split()

In [92]:
a = pd.read_csv('dataset/split/train_fold_0_seed_960630.csv')

In [96]:
a['0'].values

AttributeError: 'numpy.ndarray' object has no attribute 'to_list'

In [76]:
len(val_df)

6838

In [77]:
val_df[0:10]

['VP106/R001.png',
 'VP106/R208.png',
 'VP106/L167.png',
 'VP106/L105.png',
 'VP106/R041.png',
 'VP106/R085.png',
 'VP106/L028.png',
 'VP106/L066.png',
 'VP106/L130.png',
 'VP106/R190.png']

In [10]:
train_df

(array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

In [11]:
test_df

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]))